### ISSUE TITLE
Neuron Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/neuron#119]
**Note** 
*Some  of the usual checklist items have been removed as they were not applicable in this case. A third party (Ghent) paid for this sim to be developed so there was not the normal quoting process, and a simple quick mockup was sent as a guide*

## Design
- [x] **Design doc created** (Date: 03/15/2016)
 - [x] Make phethelp@gmail.com owner, share with phet-team
 - [x] Add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
- [x] **Legacy sim docs/info gathered**
- [x] **Learning goals and standards identified** (Date: 09/01/2014)
- [x] **Design concept complete**  (Date: 09/01/2014)
- [x] **Wireframes complete** (Date: 09/01/2014) 
- [x] **Mockups complete** (Date: 09/04/2014)
  - [x] Mockups checked for colorblind and greyscale
- [x] **Visual and interaction review of first deliverable**
- [x] **Interviews complete** (Date: //) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 02/09/2016) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher guide
  - [x] Compatible activities ([author spreadsheet] (https://docs.google.com/spreadsheets/d/1AOc1vy0HfEeJQ9sT0Vs_sr6dqmsEHfq7HWUBGQV_VQA/edit#gid=0))
  - [x] Update [Gooru spreadsheet] (https://docs.google.com/spreadsheets/d/13qvc7e71zTTjaJ2VcYhhU0rNxvH4kYFnoScVCOvvf7U/edit#gid=1717560774)
  - [x] Sim primer
  - [x] Verify credits
- [x] **Add to Edmodo**

## Implementation
- [x] **Sim repo created** (Date: 09/04/2014)
  - [x] Collaborators added (such as 3rd party, QA team, designers, etc)
  - [x] Standard label set applied
  - [x] Sim added to active repos list in chipper
  - [x] Sim suggestions doc reviewed
  - [x] Unfuddle tickets reviewed
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo
- [x] **Initial development started** (Date: 09/10/2014) 
- [x] **Sim feature complete** (Date: 01/28/2015)
- [x] **Code review complete** (Date: 12/20/2015) 
  - [x] Model description 
- [x] **PhET tweaks after sim acceptance** (Date: 01/25/2016) 
- [x] **Published** (Date: 02/29/2016) 
  - [x] Update repo README to published template

## QA
- [x] **Legacy sim tested for bugs;** issues reported in repo
- [x] **Dev testing complete** (Date: 10/26/2015)
- [x] **First release candidate** (Date: 12/22/2015)
 - [x] phethelp@gmail.com owner of test matrix, share with phet-team, add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
- [x] **Sim accepted from third party** (Date: 02/05/2015)
- [x] **Test matrix deemed complete**

**Comment by ariel-phet** [comment]
Just primer left. Assigning to @amyh-phet

**Comment by amyh-phet** [comment]
@ariel-phet    Should be completed next week.  Have recorded one version, gotten feedback from Stephanie, and just need to make a final recording.

**Comment by amyh-phet** [comment]
@ariel-phet    Checklist is complete.  Closing
